### ISSUE TITLE
 libc    : Unable to set property "ctl.interface_start" to "aidl/activity": error code: 0x20

### ISSUE THREAD

**Issue by EliasTheGrandMasterOfMistakes** [roynatech2544/android_device_samsung_a20-a20e#15]

**Comment by EliasTheGrandMasterOfMistakes** [comment]
04-11 09:27:07.087  3595  4703 W libc    : Unable to set property "ctl.interface_start" to "aidl/activity": error code: 0x20
04-11 09:27:08.086  4163  4163 W ServiceManagerCppClient: Waited one second for activity (is service started? Number of threads started in the threadpool: 16. Are binder threads started and available?)

**Comment by Royna2544** [comment]
doesn't help at all, provide full logs else am closing this issue

**Comment by EliasTheGrandMasterOfMistakes** [comment]
> doesn't help at all, provide full logs else am closing this issue

full log?
[lineagelogboot2.txt](https://github.com/eurekadevelopment/android_device_samsung_exynos7885/files/14964163/lineagelogboot2.txt)

**Comment by Royna2544** [comment]
Not dt issue, evox boots fine
