### ISSUE TITLE
[REQ] \e\ and autobuilder

### ISSUE THREAD

**Issue by MarcoRavich** [roynatech2544/android_device_samsung_a20-a20e#5]
Hi there, 1st of all thank you for your (voluntary) work !
Secondly we're sorry for posting this request here, but we don't know where it would have been better to do it.

Since we've noticed that you build a lot of (LOS-based too) ROMs, it would be great to add \e\ distro to your collection too:

"/e/OS is the leading pro-privacy operating system for smartphones. It consists of a fully deGoogled mobile operating system (OS) and carefully selected applications, together forming a privacy-enabled internal environment for mobile phones."

https://e.foundation/

If you need, here's a couple of interesting guides that may help to build it:
https://doc.e.foundation/support-topics/build-e
https://community.e.foundation/t/howto-building-e-roms-a-beginners-guide/26371

Last but not least, we've also already suggested (check [here](https://community.e.foundation/t/automated-builds-v-machine/43336)) to setup a "build (V)Machine" by modding these colab notebooks to made them device agnostic:
https://github.com/viam1-dev/colab_lineage_build
https://github.com/T110-android/colab_build

Hope can "inspire" you.

Thanks in advance.

**Comment by Gabriel2392** [comment]
Hi there.

We regret to inform you that all development for the Exynos7885 SoC (from our side) has been suspended indefinitely, and it is unlikely that we will resume our work in the future. We understand that this may cause inconvenience, and we apologize for any disruption this may have caused. Thank you for your understanding.
